[matching]
'vlc' = ''
'kitty' = ''
'firefox' = ''
'firefox-esr' = ''
'libreoffice' = ''
'libreoffice-calc' = ''
'libreoffice-writer' = ''
'Thunderbird' = ''
'thunderbird' = ''
'nemo' = ''
'spotify' = ''
'org.pwmt.zathura' = ''
'dbgate' = ''
'org.keepassxc.KeePassXC' = ''
'zoom' = '󰭹'

[other]
fallback_icon = ''
deduplicate_icons = true
