[matching]
'vlc' = ''
'foot' = ''
'zoom' = '󰭹'
'gimp' = ''
'steam' = ''
'thunar' = ''
'dbgate' = ''
'firefox' = ''
'spotify' = ''
'swayimg' = ''
'footclient' = ''
'firefox-esr' = ''
'libreoffice' = ''
'Thunderbird' = ''
'thunderbird' = ''
'calibre-gui' = ''
'virt-manager' = '󰌽'
'org.pwmt.zathura' = ''
'libreoffice-calc' = ''
'libreoffice-writer' = ''
'org.telegram.desktop' = ''
'Org.chromium.Chromium' = ''
'org.inkscape.Inkscape' = ''
'libreoffice-startcenter' = ''
'org.keepassxc.KeePassXC' = ''
'es-gob-afirma-standalone-SimpleAfirma' = ''

[other]
fallback_icon = ''
deduplicate_icons = true
